# this is the common set of command for all the plugins

MACRO(SETUP_PLUGIN PLUGIN_NAME)
	 SET(TARGET_NAME ${PLUGIN_NAME} )
	 
	 SOURCE_GROUP( "Header Files"   FILES ${TARGET_H} )
   SOURCE_GROUP( "Shader Files"   FILES ${TARGET_GLSL} )
   SOURCe_GROUP( "Template Files" FILES ${TARGET_IN} )
   
   IF(NOT TARGET_TARGETNAME)
   	SET(TARGET_TARGETNAME "${TARGET_NAME}")
   ENDIF(NOT TARGET_TARGETNAME)
   
   
   ADD_LIBRARY(${TARGET_TARGETNAME} ${SHARED_OR_STATIC}  ${TARGET_SRC} ${TARGET_H} ${TARGET_GLSL} ${TARGET_IN})
   

   IF(WIN32)
   INSTALL(TARGETS ${TARGET_TARGETNAME} RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} ARCHIVE DESTINATION ${CMAKE_INSTALL_BINDIR}  LIBRARY DESTINATION bin/  )
   	 
   ENDIF(WIN32)
 
 	SET_PROPERTY(TARGET ${TARGET_TARGETNAME} PROPERTY FOLDER "Plugins")
   
ENDMACRO(SETUP_PLUGIN)
